### ISSUE TITLE
Does this actually work with the "none" option?

### ISSUE THREAD

**Issue by callmeaponte** [krotovic/netlify-plugin-dotenv#5]
It's quite possible I'm doing something wrong, but I have the following in my `.netlify.toml` file:

```
[[plugins]]
package = "dotenv"
  [plugins.inputs]
  method = "none"
```

... yet the environment variables defined in my Netlify dashboard, are still overriding the ones defined in my local `.env` file. Is this a bug, or am I missing something?

**Comment by krotovic** [comment]
Hi, sorry for my inactivity and thank you for using this plugin.

I wanted this plugin to work like loader for definitions of the env variables with their default values and overwrite them in the dashboard for specific websites (deploys). So I actually never used that option. But it should work in theory. I'm not sure if Netlify build bot will overwrite the environments defined in the dashboard right before running the build phase.

I have just released new version of this plugin with (I hope) better functionality. It was weird from the start and I wanted to improve that.

Let me know if it helps somehow.
